type: docker
kind: pipeline
name: default

steps:
  - name: 打包博客
    image: node:16.18.1
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: blog
        path: /perry/wosperry-blog-public
    commands:
      - "npm install"
      - "npm run build"
      - "cp -r build/* /perry/wosperry-blog-public"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: blog
    host:
      path: /perry/wosperry-blog-public

trigger:
  event:
    - push